### ISSUE TITLE
[BUG] Permission flag doesn't work

### ISSUE THREAD

**Issue by csportalsk** [M1Kac/Simple-ColoredSmoke#1]
Hi. 
When Flag is set for specific permission it doesn't work. Everybody have colored smoke, not only players with specific permission.

CSS v195, ColoredSmoke v1.0.1, Linux

**Comment by M1Kac** [comment]
Thanks, 
I will check it these days.

**Comment by M1Kac** [comment]
Now it's fixed in latest version 1.0.2

**Comment by M1Kac** [comment]
Fixed in latest version 1.0.2
